all: eje1 eje2 eje3 eje4 eje5

eje1: eje1.c
	gcc -o eje1 eje1.c

eje2: eje2.c
	gcc -o eje2 eje2.c

eje3: eje3.c
	gcc -o eje3 eje3.c

eje4: eje4.c
	gcc -o eje4 eje4.c

eje5: eje5.c
	gcc -o eje5 eje5.c
