all: practica1 practica1_serial practica2

practica1: practica1.c
	gcc -o practica1 practica1.c -lpthread -lm

practica1_serial: practica1_serial.c
	gcc -o practica1_serial practica1_serial.c -lpthread -lm

practica2: practica2.c
	gcc -o practica2 practica2.c -lpthread -lm